// Injection tokens for interfaces and configuration
export const TOKENS = {
  // Configuration tokens
  CONFIG_PATH: Symbol('CONFIG_PATH'),
  WORKSPACE_ROOT: Symbol('WORKSPACE_ROOT'),

  // Service tokens (for interface injection if needed)
  FILE_SYSTEM_SERVICE: Symbol('FILE_SYSTEM_SERVICE'),
  CONFIGURATION_SERVICE: Symbol('CONFIGURATION_SERVICE'),
  IDENTIFIER_SERVICE: Symbol('IDENTIFIER_SERVICE'),
  TEMPLATE_IDENTIFIER_SERVICE: Symbol('TEMPLATE_IDENTIFIER_SERVICE'),
  VARIABLE_SUBSTITUTION_SERVICE: Symbol('VARIABLE_SUBSTITUTION_SERVICE'),
  PROJECT_MANIFEST_SERVICE: Symbol('PROJECT_MANIFEST_SERVICE'),
  TEMPLATE_SERVICE: Symbol('TEMPLATE_SERVICE'),
  PROJECT_CREATION_SERVICE: Symbol('PROJECT_CREATION_SERVICE'),
  PROJECT_VALIDATION_SERVICE: Symbol('PROJECT_VALIDATION_SERVICE'),
  PROJECT_FIX_SERVICE: Symbol('PROJECT_FIX_SERVICE'),
  PROJECT_EXTENSION_SERVICE: Symbol('PROJECT_EXTENSION_SERVICE'),
} as const;
